name: CI

on:
  push:
  pull_request:
    types: [labeled]

jobs:
  show_and_tell:
    runs-on: ubuntu-latest
    steps:
    - name: eventdata
      uses: ludeeus/action-eventdata@0.0.1

  build:
    if: ${{ github.event.label.name == 'require integration tests' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          git status
          git branch -va
          
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          comment_mode: create new
          hide_comments: all but latest
          check_run_annotations_branch: '*'
          files: '*.xml'

      - name: removelabel
        uses: buildsville/add-remove-label@v1
        if: always()
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: require integration tests
          type: remove
